server:
  port: 8989
spring:
  application:
    name: gateway
  # port configuration to zipkin
  zipkin:
    enabled: false

eureka:
  client:
    register-with-eureka: false
    # eureka credential
    service-url:
      defaultZone: http://netflix:eureka@localhost:8761/eureka